@startuml
title Mastery Task 03

'https://tiny.amazon.com/tbf5u5sn/plancorpamazplanformencohtml

enum Material {
  + CORRUGATE
  + LAMINATED_PLASTIC
}

class Packaging {
  -material: Material
  +getMass(): BigDecimal
  +canFitItem(Item): boolean
}

class Box {
  -length: BigDecimal
  -width: BigDecimal
  -height: BigDecimal
  +getLength(): BigDecimal
  +getWidth(): BigDecimal
  +getHeight(): BigDecimal
}

class PolyBag {
  -volume: BigDecimal
  +getVolume(): BigDecimal
}

Packaging *- Material
Packaging <|-- Box
Packaging <|-- PolyBag
@enduml
